import 'package:flutter/material.dart';

class RandomIcon{

    static IconData getIcon(int randomNumber){
      switch(randomNumber){
        case 1: return Icons.ac_unit;
        break;
        case 2: return Icons.access_alarm;
        break;
        case 3: return Icons.access_alarms;
        break;
        case 4: return Icons.access_time;
        break;
        case 5: return Icons.accessibility;
        break;
        case 6: return Icons.accessibility_new;
        break;
        case 7: return Icons.accessible;
        break;
        case 8: return Icons.accessible_forward;
        break;
        case 9: return Icons.account_balance;
        break;
        case 10: return Icons.account_balance_wallet;
        break;
        case 11: return Icons.account_box;
        break;
        case 12: return Icons.account_circle;
        break;
        case 13: return Icons.adb;
        break;
        case 14: return Icons.add;
        break;
        case 15: return Icons.add_a_photo;
        break;
        case 16: return Icons.add_alarm;
        break;
        case 17: return Icons.add_alert;
        break;
        case 18: return Icons.add_box;
        break;
        case 19: return Icons.add_call;
        break;
        case 20: return Icons.add_circle;
        break;
        case 21: return Icons.add_circle_outline;
        break;
        case 22: return Icons.add_comment;
        break;
        case 23: return Icons.add_location;
        break;
        case 24: return Icons.add_photo_alternate;
        break;
        case 25: return Icons.add_shopping_cart;
        break;
        case 26: return Icons.add_to_home_screen;
        break;
        case 27: return Icons.add_to_photos;
        break;
        case 28: return Icons.add_to_queue;
        break;
        case 29: return Icons.adjust;
        break;
        case 30: return Icons.airline_seat_flat;
        break;
        case 31: return Icons.airline_seat_flat_angled;
        break;
        case 32: return Icons.airline_seat_individual_suite;
        break;
        case 33: return Icons.airline_seat_legroom_extra;
        break;
        case 34: return Icons.airline_seat_legroom_normal;
        break;
        case 35: return Icons.airline_seat_legroom_reduced;
        break;
        case 36: return Icons.airline_seat_recline_extra;
        break;
        case 37: return Icons.airline_seat_recline_normal;
        break;
        case 38: return Icons.airplanemode_active;
        break;
        case 39: return Icons.airplanemode_inactive;
        break;
        case 40: return Icons.airplay;
        break;
        case 41: return Icons.airport_shuttle;
        break;
        case 42: return Icons.alarm;
        break;
        case 43: return Icons.alarm_add;
        break;
        case 44: return Icons.alarm_off;
        break;
        case 45: return Icons.alarm_on;
        break;
        case 46: return Icons.album;
        break;
        case 47: return Icons.all_inclusive;
        break;
        case 48: return Icons.all_out;
        break;
        case 49: return Icons.alternate_email;
        break;
        case 50: return Icons.android;
        break;
        case 51: return Icons.announcement;
        break;
        case 52: return Icons.apps;
        break;
        case 53: return Icons.archive;
        break;
        case 54: return Icons.arrow_back;
        break;
        case 55: return Icons.arrow_back_ios;
        break;
        case 56: return Icons.arrow_downward;
        break;
        case 57: return Icons.arrow_drop_down;
        break;
        case 58: return Icons.arrow_drop_down_circle;
        break;
        case 59: return Icons.arrow_drop_up;
        break;
        case 60: return Icons.arrow_forward;
        break;
        case 61: return Icons.arrow_forward_ios;
        break;
        case 62: return Icons.arrow_left;
        break;
        case 63: return Icons.arrow_right;
        break;
        case 64: return Icons.arrow_upward;
        break;
        case 65: return Icons.art_track;
        break;
        case 66: return Icons.aspect_ratio;
        break;
        case 67: return Icons.assessment;
        break;
        case 68: return Icons.assignment;
        break;
        case 69: return Icons.assignment_ind;
        break;
        case 70: return Icons.assignment_late;
        break;
        case 71: return Icons.assignment_return;
        break;
        case 72: return Icons.assignment_returned;
        break;
        case 73: return Icons.assignment_turned_in;
        break;
        case 74: return Icons.assistant;
        break;
        case 75: return Icons.assistant_photo;
        break;
        case 76: return Icons.atm;
        break;
        case 77: return Icons.attach_file;
        break;
        case 78: return Icons.attach_money;
        break;
        case 79: return Icons.attachment;
        break;
        case 80: return Icons.audiotrack;
        break;
        case 81: return Icons.autorenew;
        break;
        case 82: return Icons.av_timer;
        break;
        case 83: return Icons.backspace;
        break;
        case 84: return Icons.backup;
        break;
        case 85: return Icons.battery_alert;
        break;
        case 86: return Icons.battery_charging_full;
        break;
        case 87: return Icons.battery_full;
        break;
        case 88: return Icons.battery_std;
        break;
        case 89: return Icons.battery_unknown;
        break;
        case 90: return Icons.beach_access;
        break;
        case 91: return Icons.beenhere;
        break;
        case 92: return Icons.block;
        break;
        case 93: return Icons.bluetooth;
        break;
        case 94: return Icons.bluetooth_audio;
        break;
        case 95: return Icons.bluetooth_connected;
        break;
        case 96: return Icons.bluetooth_disabled;
        break;
        case 97: return Icons.bluetooth_searching;
        break;
        case 98: return Icons.blur_circular;
        break;
        case 99: return Icons.blur_linear;
        break;
        case 100: return Icons.blur_off;
        break;
        case 101: return Icons.blur_on;
        break;
        case 102: return Icons.book;
        break;
        case 103: return Icons.bookmark;
        break;
        case 104: return Icons.bookmark_border;
        break;
        case 105: return Icons.border_all;
        break;
        case 106: return Icons.border_bottom;
        break;
        case 107: return Icons.border_clear;
        break;
        case 108: return Icons.border_color;
        break;
        case 109: return Icons.border_horizontal;
        break;
        case 110: return Icons.border_inner;
        break;
        case 111: return Icons.border_left;
        break;
        case 112: return Icons.border_outer;
        break;
        case 113: return Icons.border_right;
        break;
        case 114: return Icons.border_style;
        break;
        case 115: return Icons.border_top;
        break;
        case 116: return Icons.border_vertical;
        break;
        case 117: return Icons.branding_watermark;
        break;
        case 118: return Icons.brightness_1;
        break;
        case 119: return Icons.brightness_2;
        break;
        case 120: return Icons.brightness_3;
        break;
        case 121: return Icons.brightness_4;
        break;
        case 122: return Icons.brightness_5;
        break;
        case 123: return Icons.brightness_6;
        break;
        case 124: return Icons.brightness_7;
        break;
        case 125: return Icons.brightness_auto;
        break;
        case 126: return Icons.brightness_high;
        break;
        case 127: return Icons.brightness_low;
        break;
        case 128: return Icons.brightness_medium;
        break;
        case 129: return Icons.broken_image;
        break;
        case 130: return Icons.brush;
        break;
        case 131: return Icons.bubble_chart;
        break;
        case 132: return Icons.bug_report;
        break;
        case 133: return Icons.build;
        break;
        case 134: return Icons.burst_mode;
        break;
        case 135: return Icons.business;
        break;
        case 136: return Icons.business_center;
        break;
        case 137: return Icons.cached;
        break;
        case 138: return Icons.cake;
        break;
        case 139: return Icons.calendar_today;
        break;
        case 140: return Icons.calendar_view_day;
        break;
        case 141: return Icons.call;
        break;
        case 142: return Icons.call_end;
        break;
        case 143: return Icons.call_made;
        break;
        case 144: return Icons.call_merge;
        break;
        case 145: return Icons.call_missed;
        break;
        case 146: return Icons.call_missed_outgoing;
        break;
        case 147: return Icons.call_received;
        break;
        case 148: return Icons.call_split;
        break;
        case 149: return Icons.call_to_action;
        break;
        case 150: return Icons.camera;
        break;
        case 151: return Icons.camera_alt;
        break;
        case 152: return Icons.camera_enhance;
        break;
        case 153: return Icons.camera_front;
        break;
        case 154: return Icons.camera_rear;
        break;
        case 155: return Icons.camera_roll;
        break;
        case 156: return Icons.cancel;
        break;
        case 157: return Icons.card_giftcard;
        break;
        case 158: return Icons.card_membership;
        break;
        case 159: return Icons.card_travel;
        break;
        case 160: return Icons.casino;
        break;
        case 161: return Icons.cast;
        break;
        case 162: return Icons.cast_connected;
        break;
        case 163: return Icons.category;
        break;
        case 164: return Icons.center_focus_strong;
        break;
        case 165: return Icons.center_focus_weak;
        break;
        case 166: return Icons.change_history;
        break;
        case 167: return Icons.chat;
        break;
        case 168: return Icons.chat_bubble;
        break;
        case 169: return Icons.chat_bubble_outline;
        break;
        case 170: return Icons.check;
        break;
        case 171: return Icons.check_box;
        break;
        case 172: return Icons.check_box_outline_blank;
        break;
        case 173: return Icons.check_circle;
        break;
        case 174: return Icons.check_circle_outline;
        break;
        case 175: return Icons.chevron_left;
        break;
        case 176: return Icons.chevron_right;
        break;
        case 177: return Icons.child_care;
        break;
        case 178: return Icons.child_friendly;
        break;
        case 179: return Icons.chrome_reader_mode;
        break;
        case 180: return Icons.class_;
        break;
        case 181: return Icons.clear;
        break;
        case 182: return Icons.clear_all;
        break;
        case 183: return Icons.close;
        break;
        case 184: return Icons.closed_caption;
        break;
        case 185: return Icons.cloud;
        break;
        case 186: return Icons.cloud_circle;
        break;
        case 187: return Icons.cloud_done;
        break;
        case 188: return Icons.cloud_download;
        break;
        case 189: return Icons.cloud_off;
        break;
        case 190: return Icons.cloud_queue;
        break;
        case 191: return Icons.cloud_upload;
        break;
        case 192: return Icons.code;
        break;
        case 193: return Icons.collections;
        break;
        case 194: return Icons.collections_bookmark;
        break;
        case 195: return Icons.color_lens;
        break;
        case 196: return Icons.colorize;
        break;
        case 197: return Icons.comment;
        break;
        case 198: return Icons.compare;
        break;
        case 199: return Icons.compare_arrows;
        break;
        case 200: return Icons.computer;
        break;
        case 201: return Icons.confirmation_number;
        break;
        case 202: return Icons.contact_mail;
        break;
        case 203: return Icons.contact_phone;
        break;
        case 204: return Icons.contacts;
        break;
        case 205: return Icons.content_copy;
        break;
        case 206: return Icons.content_cut;
        break;
        case 207: return Icons.content_paste;
        break;
        case 208: return Icons.control_point;
        break;
        case 209: return Icons.control_point_duplicate;
        break;
        case 210: return Icons.copyright;
        break;
        case 211: return Icons.create;
        break;
        case 212: return Icons.create_new_folder;
        break;
        case 213: return Icons.credit_card;
        break;
        case 214: return Icons.crop;
        break;
        case 215: return Icons.crop_3_2;
        break;
        case 216: return Icons.crop_5_4;
        break;
        case 217: return Icons.crop_7_5;
        break;
        case 218: return Icons.crop_16_9;
        break;
        case 219: return Icons.crop_din;
        break;
        case 220: return Icons.crop_free;
        break;
        case 221: return Icons.crop_landscape;
        break;
        case 222: return Icons.crop_original;
        break;
        case 223: return Icons.crop_portrait;
        break;
        case 224: return Icons.crop_rotate;
        break;
        case 225: return Icons.crop_square;
        break;
        case 226: return Icons.dashboard;
        break;
        case 227: return Icons.data_usage;
        break;
        case 228: return Icons.date_range;
        break;
        case 229: return Icons.dehaze;
        break;
        case 230: return Icons.delete;
        break;
        case 231: return Icons.delete_forever;
        break;
        case 232: return Icons.delete_outline;
        break;
        case 233: return Icons.delete_sweep;
        break;
        case 234: return Icons.departure_board;
        break;
        case 235: return Icons.description;
        break;
        case 236: return Icons.desktop_mac;
        break;
        case 237: return Icons.desktop_windows;
        break;
        case 238: return Icons.details;
        break;
        case 239: return Icons.developer_board;
        break;
        case 240: return Icons.developer_mode;
        break;
        case 241: return Icons.device_hub;
        break;
        case 242: return Icons.device_unknown;
        break;
        case 243: return Icons.devices;
        break;
        case 244: return Icons.devices_other;
        break;
        case 245: return Icons.dialer_sip;
        break;
        case 246: return Icons.dialpad;
        break;
        case 247: return Icons.directions;
        break;
        case 248: return Icons.directions_bike;
        break;
        case 249: return Icons.directions_boat;
        break;
        case 250: return Icons.directions_bus;
        break;
        case 251: return Icons.directions_car;
        break;
        case 252: return Icons.directions_railway;
        break;
        case 253: return Icons.directions_run;
        break;
        case 254: return Icons.directions_subway;
        break;
        case 255: return Icons.directions_transit;
        break;
        case 256: return Icons.directions_walk;
        break;
        case 257: return Icons.disc_full;
        break;
        case 258: return Icons.dns;
        break;
        case 259: return Icons.do_not_disturb;
        break;
        case 260: return Icons.do_not_disturb_alt;
        break;
        case 261: return Icons.do_not_disturb_off;
        break;
        case 262: return Icons.do_not_disturb_on;
        break;
        case 263: return Icons.dock;
        break;
        case 264: return Icons.domain;
        break;
        case 265: return Icons.done;
        break;
        case 266: return Icons.done_all;
        break;
        case 267: return Icons.done_outline;
        break;
        case 268: return Icons.donut_large;
        break;
        case 269: return Icons.donut_small;
        break;
        case 270: return Icons.drafts;
        break;
        case 271: return Icons.drag_handle;
        break;
        case 272: return Icons.drive_eta;
        break;
        case 273: return Icons.dvr;
        break;
        case 274: return Icons.edit;
        break;
        case 275: return Icons.edit_attributes;
        break;
        case 276: return Icons.edit_location;
        break;
        case 277: return Icons.eject;
        break;
        case 278: return Icons.email;
        break;
        case 279: return Icons.enhanced_encryption;
        break;
        case 280: return Icons.equalizer;
        break;
        case 281: return Icons.error;
        break;
        case 282: return Icons.error_outline;
        break;
        case 283: return Icons.euro_symbol;
        break;
        case 284: return Icons.ev_station;
        break;
        case 285: return Icons.event;
        break;
        case 286: return Icons.event_available;
        break;
        case 287: return Icons.event_busy;
        break;
        case 288: return Icons.event_note;
        break;
        case 289: return Icons.event_seat;
        break;
        case 290: return Icons.exit_to_app;
        break;
        case 291: return Icons.expand_less;
        break;
        case 292: return Icons.expand_more;
        break;
        case 293: return Icons.explicit;
        break;
        case 294: return Icons.explore;
        break;
        case 295: return Icons.exposure;
        break;
        case 296: return Icons.exposure_neg_1;
        break;
        case 297: return Icons.exposure_neg_2;
        break;
        case 298: return Icons.exposure_plus_1;
        break;
        case 299: return Icons.exposure_plus_2;
        break;
        case 300: return Icons.exposure_zero;
        break;
        case 301: return Icons.extension;
        break;
        case 302: return Icons.face;
        break;
        case 303: return Icons.fast_forward;
        break;
        case 304: return Icons.fast_rewind;
        break;
        case 305: return Icons.fastfood;
        break;
        case 306: return Icons.favorite;
        break;
        case 307: return Icons.favorite_border;
        break;
        case 308: return Icons.featured_play_list;
        break;
        case 309: return Icons.featured_video;
        break;
        case 310: return Icons.feedback;
        break;
        case 311: return Icons.fiber_dvr;
        break;
        case 312: return Icons.fiber_manual_record;
        break;
        case 313: return Icons.fiber_new;
        break;
        case 314: return Icons.fiber_pin;
        break;
        case 315: return Icons.fiber_smart_record;
        break;
        case 316: return Icons.file_download;
        break;
        case 317: return Icons.file_upload;
        break;
        case 318: return Icons.filter;
        break;
        case 319: return Icons.filter_1;
        break;
        case 320: return Icons.filter_2;
        break;
        case 321: return Icons.filter_3;
        break;
        case 322: return Icons.filter_4;
        break;
        case 323: return Icons.filter_5;
        break;
        case 324: return Icons.filter_6;
        break;
        case 325: return Icons.filter_7;
        break;
        case 326: return Icons.filter_8;
        break;
        case 327: return Icons.filter_9;
        break;
        case 328: return Icons.filter_9_plus;
        break;
        case 329: return Icons.filter_b_and_w;
        break;
        case 330: return Icons.filter_center_focus;
        break;
        case 331: return Icons.filter_drama;
        break;
        case 332: return Icons.filter_frames;
        break;
        case 333: return Icons.filter_hdr;
        break;
        case 334: return Icons.filter_list;
        break;
        case 335: return Icons.filter_none;
        break;
        case 336: return Icons.filter_tilt_shift;
        break;
        case 337: return Icons.filter_vintage;
        break;
        case 338: return Icons.find_in_page;
        break;
        case 339: return Icons.find_replace;
        break;
        case 340: return Icons.fingerprint;
        break;
        case 341: return Icons.first_page;
        break;
        case 342: return Icons.fitness_center;
        break;
        case 343: return Icons.flag;
        break;
        case 344: return Icons.flare;
        break;
        case 345: return Icons.flash_auto;
        break;
        case 346: return Icons.flash_off;
        break;
        case 347: return Icons.flash_on;
        break;
        case 348: return Icons.flight;
        break;
        case 349: return Icons.flight_land;
        break;
        case 350: return Icons.flight_takeoff;
        break;
        case 351: return Icons.flip;
        break;
        case 352: return Icons.flip_to_back;
        break;
        case 353: return Icons.flip_to_front;
        break;
        case 354: return Icons.folder;
        break;
        case 355: return Icons.folder_open;
        break;
        case 356: return Icons.folder_shared;
        break;
        case 357: return Icons.folder_special;
        break;
        case 358: return Icons.font_download;
        break;
        case 359: return Icons.format_align_center;
        break;
        case 360: return Icons.format_align_justify;
        break;
        case 361: return Icons.format_align_left;
        break;
        case 362: return Icons.format_align_right;
        break;
        case 363: return Icons.format_bold;
        break;
        case 364: return Icons.format_clear;
        break;
        case 365: return Icons.format_color_fill;
        break;
        case 366: return Icons.format_color_reset;
        break;
        case 367: return Icons.format_color_text;
        break;
        case 368: return Icons.format_indent_decrease;
        break;
        case 369: return Icons.format_indent_increase;
        break;
        case 370: return Icons.format_italic;
        break;
        case 371: return Icons.format_line_spacing;
        break;
        case 372: return Icons.format_list_bulleted;
        break;
        case 373: return Icons.format_list_numbered;
        break;
        case 374: return Icons.format_list_numbered_rtl;
        break;
        case 375: return Icons.format_paint;
        break;
        case 376: return Icons.format_quote;
        break;
        case 377: return Icons.format_shapes;
        break;
        case 378: return Icons.format_size;
        break;
        case 379: return Icons.format_strikethrough;
        break;
        case 380: return Icons.format_textdirection_l_to_r;
        break;
        case 381: return Icons.format_textdirection_r_to_l;
        break;
        case 382: return Icons.format_underlined;
        break;
        case 383: return Icons.forum;
        break;
        case 384: return Icons.forward;
        break;
        case 385: return Icons.forward_5;
        break;
        case 386: return Icons.forward_10;
        break;
        case 387: return Icons.forward_30;
        break;
        case 388: return Icons.four_k;
        break;
        case 389: return Icons.free_breakfast;
        break;
        case 390: return Icons.fullscreen;
        break;
        case 391: return Icons.fullscreen_exit;
        break;
        case 392: return Icons.functions;
        break;
        case 393: return Icons.g_translate;
        break;
        case 394: return Icons.gamepad;
        break;
        case 395: return Icons.games;
        break;
        case 396: return Icons.gavel;
        break;
        case 397: return Icons.gesture;
        break;
        case 398: return Icons.get_app;
        break;
        case 399: return Icons.gif;
        break;
        case 400: return Icons.golf_course;
        break;
        case 401: return Icons.gps_fixed;
        break;
        case 402: return Icons.gps_not_fixed;
        break;
        case 403: return Icons.gps_off;
        break;
        case 404: return Icons.grade;
        break;
        case 405: return Icons.gradient;
        break;
        case 406: return Icons.grain;
        break;
        case 407: return Icons.graphic_eq;
        break;
        case 408: return Icons.grid_off;
        break;
        case 409: return Icons.grid_on;
        break;
        case 410: return Icons.group;
        break;
        case 411: return Icons.group_add;
        break;
        case 412: return Icons.group_work;
        break;
        case 413: return Icons.hd;
        break;
        case 414: return Icons.hdr_off;
        break;
        case 415: return Icons.hdr_on;
        break;
        case 416: return Icons.hdr_strong;
        break;
        case 417: return Icons.hdr_weak;
        break;
        case 418: return Icons.headset;
        break;
        case 419: return Icons.headset_mic;
        break;
        case 420: return Icons.headset_off;
        break;
        case 421: return Icons.healing;
        break;
        case 422: return Icons.hearing;
        break;
        case 423: return Icons.help;
        break;
        case 424: return Icons.help_outline;
        break;
        case 425: return Icons.high_quality;
        break;
        case 426: return Icons.highlight;
        break;
        case 427: return Icons.highlight_off;
        break;
        case 428: return Icons.history;
        break;
        case 429: return Icons.home;
        break;
        case 430: return Icons.hot_tub;
        break;
        case 431: return Icons.hotel;
        break;
        case 432: return Icons.hourglass_empty;
        break;
        case 433: return Icons.hourglass_full;
        break;
        case 434: return Icons.http;
        break;
        case 435: return Icons.https;
        break;
        case 436: return Icons.image;
        break;
        case 437: return Icons.image_aspect_ratio;
        break;
        case 438: return Icons.import_contacts;
        break;
        case 439: return Icons.import_export;
        break;
        case 440: return Icons.important_devices;
        break;
        case 441: return Icons.inbox;
        break;
        case 442: return Icons.indeterminate_check_box;
        break;
        case 443: return Icons.info;
        break;
        case 444: return Icons.info_outline;
        break;
        case 445: return Icons.input;
        break;
        case 446: return Icons.insert_chart;
        break;
        case 447: return Icons.insert_comment;
        break;
        case 448: return Icons.insert_drive_file;
        break;
        case 449: return Icons.insert_emoticon;
        break;
        case 450: return Icons.insert_invitation;
        break;
        case 451: return Icons.insert_link;
        break;
        case 452: return Icons.insert_photo;
        break;
        case 453: return Icons.invert_colors;
        break;
        case 454: return Icons.invert_colors_off;
        break;
        case 455: return Icons.iso;
        break;
        case 456: return Icons.keyboard;
        break;
        case 457: return Icons.keyboard_arrow_down;
        break;
        case 458: return Icons.keyboard_arrow_left;
        break;
        case 459: return Icons.keyboard_arrow_right;
        break;
        case 460: return Icons.keyboard_arrow_up;
        break;
        case 461: return Icons.keyboard_backspace;
        break;
        case 462: return Icons.keyboard_capslock;
        break;
        case 463: return Icons.keyboard_hide;
        break;
        case 464: return Icons.keyboard_return;
        break;
        case 465: return Icons.keyboard_tab;
        break;
        case 466: return Icons.keyboard_voice;
        break;
        case 467: return Icons.kitchen;
        break;
        case 468: return Icons.label;
        break;
        case 469: return Icons.label_important;
        break;
        case 470: return Icons.label_outline;
        break;
        case 471: return Icons.landscape;
        break;
        case 472: return Icons.language;
        break;
        case 473: return Icons.laptop;
        break;
        case 474: return Icons.laptop_chromebook;
        break;
        case 475: return Icons.laptop_mac;
        break;
        case 476: return Icons.laptop_windows;
        break;
        case 477: return Icons.last_page;
        break;
        case 478: return Icons.launch;
        break;
        case 479: return Icons.layers;
        break;
        case 480: return Icons.layers_clear;
        break;
        case 481: return Icons.leak_add;
        break;
        case 482: return Icons.leak_remove;
        break;
        case 483: return Icons.lens;
        break;
        case 484: return Icons.library_add;
        break;
        case 485: return Icons.library_books;
        break;
        case 486: return Icons.library_music;
        break;
        case 487: return Icons.lightbulb_outline;
        break;
        case 488: return Icons.line_style;
        break;
        case 489: return Icons.line_weight;
        break;
        case 490: return Icons.linear_scale;
        break;
        case 491: return Icons.link;
        break;
        case 492: return Icons.link_off;
        break;
        case 493: return Icons.linked_camera;
        break;
        case 494: return Icons.list;
        break;
        case 495: return Icons.live_help;
        break;
        case 496: return Icons.live_tv;
        break;
        case 497: return Icons.local_activity;
        break;
        case 498: return Icons.local_airport;
        break;
        case 499: return Icons.local_atm;
        break;
        case 500: return Icons.local_bar;
        break;
        case 501: return Icons.local_cafe;
        break;
        case 502: return Icons.local_car_wash;
        break;
        case 503: return Icons.local_convenience_store;
        break;
        case 504: return Icons.local_dining;
        break;
        case 505: return Icons.local_drink;
        break;
        case 506: return Icons.local_florist;
        break;
        case 507: return Icons.local_gas_station;
        break;
        case 508: return Icons.local_grocery_store;
        break;
        case 509: return Icons.local_hospital;
        break;
        case 510: return Icons.local_hotel;
        break;
        case 511: return Icons.local_laundry_service;
        break;
        case 512: return Icons.local_library;
        break;
        case 513: return Icons.local_mall;
        break;
        case 514: return Icons.local_movies;
        break;
        case 515: return Icons.local_offer;
        break;
        case 516: return Icons.local_parking;
        break;
        case 517: return Icons.local_pharmacy;
        break;
        case 518: return Icons.local_phone;
        break;
        case 519: return Icons.local_pizza;
        break;
        case 520: return Icons.local_play;
        break;
        case 521: return Icons.local_post_office;
        break;
        case 522: return Icons.local_printshop;
        break;
        case 523: return Icons.local_see;
        break;
        case 524: return Icons.local_shipping;
        break;
        case 525: return Icons.local_taxi;
        break;
        case 526: return Icons.location_city;
        break;
        case 527: return Icons.location_disabled;
        break;
        case 528: return Icons.location_off;
        break;
        case 529: return Icons.location_on;
        break;
        case 530: return Icons.location_searching;
        break;
        case 531: return Icons.lock;
        break;
        case 532: return Icons.lock_open;
        break;
        case 533: return Icons.lock_outline;
        break;
        case 534: return Icons.looks;
        break;
        case 535: return Icons.looks_3;
        break;
        case 536: return Icons.looks_4;
        break;
        case 537: return Icons.looks_5;
        break;
        case 538: return Icons.looks_6;
        break;
        case 539: return Icons.looks_one;
        break;
        case 540: return Icons.looks_two;
        break;
        case 541: return Icons.loop;
        break;
        case 542: return Icons.loupe;
        break;
        case 543: return Icons.low_priority;
        break;
        case 544: return Icons.loyalty;
        break;
        case 545: return Icons.mail;
        break;
        case 546: return Icons.mail_outline;
        break;
        case 547: return Icons.map;
        break;
        case 548: return Icons.markunread;
        break;
        case 549: return Icons.markunread_mailbox;
        break;
        case 550: return Icons.maximize;
        break;
        case 551: return Icons.memory;
        break;
        case 552: return Icons.menu;
        break;
        case 553: return Icons.merge_type;
        break;
        case 554: return Icons.message;
        break;
        case 555: return Icons.mic;
        break;
        case 556: return Icons.mic_none;
        break;
        case 557: return Icons.mic_off;
        break;
        case 558: return Icons.minimize;
        break;
        case 559: return Icons.missed_video_call;
        break;
        case 560: return Icons.mms;
        break;
        case 561: return Icons.mobile_screen_share;
        break;
        case 562: return Icons.mode_comment;
        break;
        case 563: return Icons.mode_edit;
        break;
        case 564: return Icons.monetization_on;
        break;
        case 565: return Icons.money_off;
        break;
        case 566: return Icons.monochrome_photos;
        break;
        case 567: return Icons.mood;
        break;
        case 568: return Icons.mood_bad;
        break;
        case 569: return Icons.more;
        break;
        case 570: return Icons.more_horiz;
        break;
        case 571: return Icons.more_vert;
        break;
        case 572: return Icons.motorcycle;
        break;
        case 573: return Icons.mouse;
        break;
        case 574: return Icons.move_to_inbox;
        break;
        case 575: return Icons.movie;
        break;
        case 576: return Icons.movie_creation;
        break;
        case 577: return Icons.movie_filter;
        break;
        case 578: return Icons.multiline_chart;
        break;
        case 579: return Icons.music_note;
        break;
        case 580: return Icons.music_video;
        break;
        case 581: return Icons.my_location;
        break;
        case 582: return Icons.nature;
        break;
        case 583: return Icons.nature_people;
        break;
        case 584: return Icons.navigate_before;
        break;
        case 585: return Icons.navigate_next;
        break;
        case 586: return Icons.navigation;
        break;
        case 587: return Icons.near_me;
        break;
        case 588: return Icons.network_cell;
        break;
        case 589: return Icons.network_check;
        break;
        case 590: return Icons.network_locked;
        break;
        case 591: return Icons.network_wifi;
        break;
        case 592: return Icons.new_releases;
        break;
        case 593: return Icons.next_week;
        break;
        case 594: return Icons.nfc;
        break;
        case 595: return Icons.no_encryption;
        break;
        case 596: return Icons.no_sim;
        break;
        case 597: return Icons.not_interested;
        break;
        case 598: return Icons.not_listed_location;
        break;
        case 599: return Icons.note;
        break;
        case 600: return Icons.note_add;
        break;
        case 601: return Icons.notification_important;
        break;
        case 602: return Icons.notifications;
        break;
        case 603: return Icons.notifications_active;
        break;
        case 604: return Icons.notifications_none;
        break;
        case 605: return Icons.notifications_off;
        break;
        case 606: return Icons.notifications_paused;
        break;
        case 607: return Icons.offline_bolt;
        break;
        case 608: return Icons.offline_pin;
        break;
        case 609: return Icons.ondemand_video;
        break;
        case 610: return Icons.opacity;
        break;
        case 611: return Icons.open_in_browser;
        break;
        case 612: return Icons.open_in_new;
        break;
        case 613: return Icons.open_with;
        break;
        case 614: return Icons.outlined_flag;
        break;
        case 615: return Icons.pages;
        break;
        case 616: return Icons.pageview;
        break;
        case 617: return Icons.palette;
        break;
        case 618: return Icons.pan_tool;
        break;
        case 619: return Icons.panorama;
        break;
        case 620: return Icons.panorama_fish_eye;
        break;
        case 621: return Icons.panorama_horizontal;
        break;
        case 622: return Icons.panorama_vertical;
        break;
        case 623: return Icons.panorama_wide_angle;
        break;
        case 624: return Icons.party_mode;
        break;
        case 625: return Icons.pause;
        break;
        case 626: return Icons.pause_circle_filled;
        break;
        case 627: return Icons.pause_circle_outline;
        break;
        case 628: return Icons.payment;
        break;
        case 629: return Icons.people;
        break;
        case 630: return Icons.people_outline;
        break;
        case 631: return Icons.perm_camera_mic;
        break;
        case 632: return Icons.perm_contact_calendar;
        break;
        case 633: return Icons.perm_data_setting;
        break;
        case 634: return Icons.perm_device_information;
        break;
        case 635: return Icons.perm_identity;
        break;
        case 636: return Icons.perm_media;
        break;
        case 637: return Icons.perm_phone_msg;
        break;
        case 638: return Icons.perm_scan_wifi;
        break;
        case 639: return Icons.person;
        break;
        case 640: return Icons.person_add;
        break;
        case 641: return Icons.person_outline;
        break;
        case 642: return Icons.person_pin;
        break;
        case 643: return Icons.person_pin_circle;
        break;
        case 644: return Icons.personal_video;
        break;
        case 645: return Icons.pets;
        break;
        case 646: return Icons.phone;
        break;
        case 647: return Icons.phone_android;
        break;
        case 648: return Icons.phone_bluetooth_speaker;
        break;
        case 649: return Icons.phone_forwarded;
        break;
        case 650: return Icons.phone_in_talk;
        break;
        case 651: return Icons.phone_iphone;
        break;
        case 652: return Icons.phone_locked;
        break;
        case 653: return Icons.phone_missed;
        break;
        case 654: return Icons.phone_paused;
        break;
        case 655: return Icons.phonelink;
        break;
        case 656: return Icons.phonelink_erase;
        break;
        case 657: return Icons.phonelink_lock;
        break;
        case 658: return Icons.phonelink_off;
        break;
        case 659: return Icons.phonelink_ring;
        break;
        case 660: return Icons.phonelink_setup;
        break;
        case 661: return Icons.photo;
        break;
        case 662: return Icons.photo_album;
        break;
        case 663: return Icons.photo_camera;
        break;
        case 664: return Icons.photo_filter;
        break;
        case 665: return Icons.photo_library;
        break;
        case 666: return Icons.photo_size_select_actual;
        break;
        case 667: return Icons.photo_size_select_large;
        break;
        case 668: return Icons.photo_size_select_small;
        break;
        case 669: return Icons.picture_as_pdf;
        break;
        case 670: return Icons.picture_in_picture;
        break;
        case 671: return Icons.picture_in_picture_alt;
        break;
        case 672: return Icons.pie_chart;
        break;
        case 673: return Icons.pie_chart_outlined;
        break;
        case 674: return Icons.pin_drop;
        break;
        case 675: return Icons.place;
        break;
        case 676: return Icons.play_arrow;
        break;
        case 677: return Icons.play_circle_filled;
        break;
        case 678: return Icons.play_circle_outline;
        break;
        case 679: return Icons.play_for_work;
        break;
        case 680: return Icons.playlist_add;
        break;
        case 681: return Icons.playlist_add_check;
        break;
        case 682: return Icons.playlist_play;
        break;
        case 683: return Icons.plus_one;
        break;
        case 684: return Icons.poll;
        break;
        case 685: return Icons.polymer;
        break;
        case 686: return Icons.pool;
        break;
        case 687: return Icons.portable_wifi_off;
        break;
        case 688: return Icons.portrait;
        break;
        case 689: return Icons.power;
        break;
        case 690: return Icons.power_input;
        break;
        case 691: return Icons.power_settings_new;
        break;
        case 692: return Icons.pregnant_woman;
        break;
        case 693: return Icons.present_to_all;
        break;
        case 694: return Icons.print;
        break;
        case 695: return Icons.priority_high;
        break;
        case 696: return Icons.public;
        break;
        case 697: return Icons.publish;
        break;
        case 698: return Icons.query_builder;
        break;
        case 699: return Icons.question_answer;
        break;
        case 700: return Icons.queue;
        break;
        case 701: return Icons.queue_music;
        break;
        case 702: return Icons.queue_play_next;
        break;
        case 703: return Icons.radio;
        break;
        case 704: return Icons.radio_button_checked;
        break;
        case 705: return Icons.radio_button_unchecked;
        break;
        case 706: return Icons.rate_review;
        break;
        case 707: return Icons.receipt;
        break;
        case 708: return Icons.recent_actors;
        break;
        case 709: return Icons.record_voice_over;
        break;
        case 710: return Icons.redeem;
        break;
        case 711: return Icons.redo;
        break;
        case 712: return Icons.refresh;
        break;
        case 713: return Icons.remove;
        break;
        case 714: return Icons.remove_circle;
        break;
        case 715: return Icons.remove_circle_outline;
        break;
        case 716: return Icons.remove_from_queue;
        break;
        case 717: return Icons.remove_red_eye;
        break;
        case 718: return Icons.remove_shopping_cart;
        break;
        case 719: return Icons.reorder;
        break;
        case 720: return Icons.repeat;
        break;
        case 721: return Icons.repeat_one;
        break;
        case 722: return Icons.replay;
        break;
        case 723: return Icons.replay_5;
        break;
        case 724: return Icons.replay_10;
        break;
        case 725: return Icons.replay_30;
        break;
        case 726: return Icons.reply;
        break;
        case 727: return Icons.reply_all;
        break;
        case 728: return Icons.report;
        break;
        case 729: return Icons.report_off;
        break;
        case 730: return Icons.report_problem;
        break;
        case 731: return Icons.restaurant;
        break;
        case 732: return Icons.restaurant_menu;
        break;
        case 733: return Icons.restore;
        break;
        case 734: return Icons.restore_from_trash;
        break;
        case 735: return Icons.restore_page;
        break;
        case 736: return Icons.ring_volume;
        break;
        case 737: return Icons.room;
        break;
        case 738: return Icons.room_service;
        break;
        case 739: return Icons.rotate_90_degrees_ccw;
        break;
        case 740: return Icons.rotate_left;
        break;
        case 741: return Icons.rotate_right;
        break;
        case 742: return Icons.rounded_corner;
        break;
        case 743: return Icons.router;
        break;
        case 744: return Icons.rowing;
        break;
        case 745: return Icons.rss_feed;
        break;
        case 746: return Icons.rv_hookup;
        break;
        case 747: return Icons.satellite;
        break;
        case 748: return Icons.save;
        break;
        case 749: return Icons.save_alt;
        break;
        case 750: return Icons.scanner;
        break;
        case 751: return Icons.scatter_plot;
        break;
        case 752: return Icons.schedule;
        break;
        case 753: return Icons.school;
        break;
        case 754: return Icons.score;
        break;
        case 755: return Icons.screen_lock_landscape;
        break;
        case 756: return Icons.screen_lock_portrait;
        break;
        case 757: return Icons.screen_lock_rotation;
        break;
        case 758: return Icons.screen_rotation;
        break;
        case 759: return Icons.screen_share;
        break;
        case 760: return Icons.sd_card;
        break;
        case 761: return Icons.sd_storage;
        break;
        case 762: return Icons.search;
        break;
        case 763: return Icons.security;
        break;
        case 764: return Icons.select_all;
        break;
        case 765: return Icons.send;
        break;
        case 766: return Icons.sentiment_dissatisfied;
        break;
        case 767: return Icons.sentiment_neutral;
        break;
        case 768: return Icons.sentiment_satisfied;
        break;
        case 769: return Icons.sentiment_very_dissatisfied;
        break;
        case 770: return Icons.sentiment_very_satisfied;
        break;
        case 771: return Icons.settings;
        break;
        case 772: return Icons.settings_applications;
        break;
        case 773: return Icons.settings_backup_restore;
        break;
        case 774: return Icons.settings_bluetooth;
        break;
        case 775: return Icons.settings_brightness;
        break;
        case 776: return Icons.settings_cell;
        break;
        case 777: return Icons.settings_ethernet;
        break;
        case 778: return Icons.settings_input_antenna;
        break;
        case 779: return Icons.settings_input_component;
        break;
        case 780: return Icons.settings_input_composite;
        break;
        case 781: return Icons.settings_input_hdmi;
        break;
        case 782: return Icons.settings_input_svideo;
        break;
        case 783: return Icons.settings_overscan;
        break;
        case 784: return Icons.settings_phone;
        break;
        case 785: return Icons.settings_power;
        break;
        case 786: return Icons.settings_remote;
        break;
        case 787: return Icons.settings_system_daydream;
        break;
        case 788: return Icons.settings_voice;
        break;
        case 789: return Icons.share;
        break;
        case 790: return Icons.shop;
        break;
        case 791: return Icons.shop_two;
        break;
        case 792: return Icons.shopping_basket;
        break;
        case 793: return Icons.shopping_cart;
        break;
        case 794: return Icons.short_text;
        break;
        case 795: return Icons.show_chart;
        break;
        case 796: return Icons.shuffle;
        break;
        case 797: return Icons.shutter_speed;
        break;
        case 798: return Icons.signal_cellular_4_bar;
        break;
        case 799: return Icons.signal_cellular_connected_no_internet_4_bar;
        break;
        case 800: return Icons.signal_cellular_no_sim;
        break;
        case 801: return Icons.signal_cellular_null;
        break;
        case 802: return Icons.signal_cellular_off;
        break;
        case 803: return Icons.signal_wifi_4_bar;
        break;
        case 804: return Icons.signal_wifi_4_bar_lock;
        break;
        case 805: return Icons.signal_wifi_off;
        break;
        case 806: return Icons.sim_card;
        break;
        case 807: return Icons.sim_card_alert;
        break;
        case 808: return Icons.skip_next;
        break;
        case 809: return Icons.skip_previous;
        break;
        case 810: return Icons.slideshow;
        break;
        case 811: return Icons.slow_motion_video;
        break;
        case 812: return Icons.smartphone;
        break;
        case 813: return Icons.smoke_free;
        break;
        case 814: return Icons.smoking_rooms;
        break;
        case 815: return Icons.sms;
        break;
        case 816: return Icons.sms_failed;
        break;
        case 817: return Icons.snooze;
        break;
        case 818: return Icons.sort;
        break;
        case 819: return Icons.sort_by_alpha;
        break;
        case 820: return Icons.spa;
        break;
        case 821: return Icons.space_bar;
        break;
        case 822: return Icons.speaker;
        break;
        case 823: return Icons.speaker_group;
        break;
        case 824: return Icons.speaker_notes;
        break;
        case 825: return Icons.speaker_notes_off;
        break;
        case 826: return Icons.speaker_phone;
        break;
        case 827: return Icons.spellcheck;
        break;
        case 828: return Icons.star;
        break;
        case 829: return Icons.star_border;
        break;
        case 830: return Icons.star_half;
        break;
        case 831: return Icons.stars;
        break;
        case 832: return Icons.stay_current_landscape;
        break;
        case 833: return Icons.stay_current_portrait;
        break;
        case 834: return Icons.stay_primary_landscape;
        break;
        case 835: return Icons.stay_primary_portrait;
        break;
        case 836: return Icons.stop;
        break;
        case 837: return Icons.stop_screen_share;
        break;
        case 838: return Icons.storage;
        break;
        case 839: return Icons.store;
        break;
        case 840: return Icons.store_mall_directory;
        break;
        case 841: return Icons.straighten;
        break;
        case 842: return Icons.streetview;
        break;
        case 843: return Icons.strikethrough_s;
        break;
        case 844: return Icons.style;
        break;
        case 845: return Icons.subdirectory_arrow_left;
        break;
        case 846: return Icons.subdirectory_arrow_right;
        break;
        case 847: return Icons.subject;
        break;
        case 848: return Icons.subscriptions;
        break;
        case 849: return Icons.subtitles;
        break;
        case 850: return Icons.subway;
        break;
        case 851: return Icons.supervised_user_circle;
        break;
        case 852: return Icons.supervisor_account;
        break;
        case 853: return Icons.surround_sound;
        break;
        case 854: return Icons.swap_calls;
        break;
        case 855: return Icons.swap_horiz;
        break;
        case 856: return Icons.swap_horizontal_circle;
        break;
        case 857: return Icons.swap_vert;
        break;
        case 858: return Icons.swap_vertical_circle;
        break;
        case 859: return Icons.switch_camera;
        break;
        case 860: return Icons.switch_video;
        break;
        case 861: return Icons.sync;
        break;
        case 862: return Icons.sync_disabled;
        break;
        case 863: return Icons.sync_problem;
        break;
        case 864: return Icons.system_update;
        break;
        case 865: return Icons.system_update_alt;
        break;
        case 866: return Icons.tab;
        break;
        case 867: return Icons.tab_unselected;
        break;
        case 868: return Icons.table_chart;
        break;
        case 869: return Icons.tablet;
        break;
        case 870: return Icons.tablet_android;
        break;
        case 871: return Icons.tablet_mac;
        break;
        case 872: return Icons.tag_faces;
        break;
        case 873: return Icons.tap_and_play;
        break;
        case 874: return Icons.terrain;
        break;
        case 875: return Icons.text_fields;
        break;
        case 876: return Icons.text_format;
        break;
        case 877: return Icons.text_rotate_up;
        break;
        case 878: return Icons.text_rotate_vertical;
        break;
        case 879: return Icons.text_rotation_angledown;
        break;
        case 880: return Icons.text_rotation_angleup;
        break;
        case 881: return Icons.text_rotation_down;
        break;
        case 882: return Icons.text_rotation_none;
        break;
        case 883: return Icons.textsms;
        break;
        case 884: return Icons.texture;
        break;
        case 885: return Icons.theaters;
        break;
        case 886: return Icons.threed_rotation;
        break;
        case 887: return Icons.threesixty;
        break;
        case 888: return Icons.thumb_down;
        break;
        case 889: return Icons.thumb_up;
        break;
        case 890: return Icons.thumbs_up_down;
        break;
        case 891: return Icons.time_to_leave;
        break;
        case 892: return Icons.timelapse;
        break;
        case 893: return Icons.timeline;
        break;
        case 894: return Icons.timer;
        break;
        case 895: return Icons.timer_3;
        break;
        case 896: return Icons.timer_10;
        break;
        case 897: return Icons.timer_off;
        break;
        case 898: return Icons.title;
        break;
        case 899: return Icons.toc;
        break;
        case 900: return Icons.today;
        break;
        case 901: return Icons.toll;
        break;
        case 902: return Icons.tonality;
        break;
        case 903: return Icons.touch_app;
        break;
        case 904: return Icons.toys;
        break;
        case 905: return Icons.track_changes;
        break;
        case 906: return Icons.traffic;
        break;
        case 907: return Icons.train;
        break;
        case 908: return Icons.tram;
        break;
        case 909: return Icons.transfer_within_a_station;
        break;
        case 910: return Icons.transform;
        break;
        case 911: return Icons.transit_enterexit;
        break;
        case 912: return Icons.translate;
        break;
        case 913: return Icons.trending_down;
        break;
        case 914: return Icons.trending_flat;
        break;
        case 915: return Icons.trending_up;
        break;
        case 916: return Icons.trip_origin;
        break;
        case 917: return Icons.tune;
        break;
        case 918: return Icons.turned_in;
        break;
        case 919: return Icons.turned_in_not;
        break;
        case 920: return Icons.tv;
        break;
        case 921: return Icons.unarchive;
        break;
        case 922: return Icons.undo;
        break;
        case 923: return Icons.unfold_less;
        break;
        case 924: return Icons.unfold_more;
        break;
        case 925: return Icons.update;
        break;
        case 926: return Icons.usb;
        break;
        case 927: return Icons.verified_user;
        break;
        case 928: return Icons.vertical_align_bottom;
        break;
        case 929: return Icons.vertical_align_center;
        break;
        case 930: return Icons.vertical_align_top;
        break;
        case 931: return Icons.vibration;
        break;
        case 932: return Icons.video_call;
        break;
        case 933: return Icons.video_label;
        break;
        case 934: return Icons.video_library;
        break;
        case 935: return Icons.videocam;
        break;
        case 936: return Icons.videocam_off;
        break;
        case 937: return Icons.videogame_asset;
        break;
        case 938: return Icons.view_agenda;
        break;
        case 939: return Icons.view_array;
        break;
        case 940: return Icons.view_carousel;
        break;
        case 941: return Icons.view_column;
        break;
        case 942: return Icons.view_comfy;
        break;
        case 943: return Icons.view_compact;
        break;
        case 944: return Icons.view_day;
        break;
        case 945: return Icons.view_headline;
        break;
        case 946: return Icons.view_list;
        break;
        case 947: return Icons.view_module;
        break;
        case 948: return Icons.view_quilt;
        break;
        case 949: return Icons.view_stream;
        break;
        case 950: return Icons.view_week;
        break;
        case 951: return Icons.vignette;
        break;
        case 952: return Icons.visibility;
        break;
        case 953: return Icons.visibility_off;
        break;
        case 954: return Icons.voice_chat;
        break;
        case 955: return Icons.voicemail;
        break;
        case 956: return Icons.volume_down;
        break;
        case 957: return Icons.volume_mute;
        break;
        case 958: return Icons.volume_off;
        break;
        case 959: return Icons.volume_up;
        break;
        case 960: return Icons.vpn_key;
        break;
        case 961: return Icons.vpn_lock;
        break;
        case 962: return Icons.wallpaper;
        break;
        case 963: return Icons.warning;
        break;
        case 964: return Icons.watch;
        break;
        case 965: return Icons.watch_later;
        break;
        case 966: return Icons.wb_auto;
        break;
        case 967: return Icons.wb_cloudy;
        break;
        case 968: return Icons.wb_incandescent;
        break;
        case 969: return Icons.wb_iridescent;
        break;
        case 970: return Icons.wb_sunny;
        break;
        case 971: return Icons.wc;
        break;
        case 972: return Icons.web;
        break;
        case 973: return Icons.web_asset;
        break;
        case 974: return Icons.weekend;
        break;
        case 975: return Icons.whatshot;
        break;
        case 976: return Icons.widgets;
        break;
        case 977: return Icons.wifi;
        break;
        case 978: return Icons.wifi_lock;
        break;
        case 979: return Icons.wifi_tethering;
        break;
        case 980: return Icons.work;
        break;
        case 981: return Icons.wrap_text;
        break;
        case 982: return Icons.youtube_searched_for;
        break;
        case 983: return Icons.zoom_in;
        break;
        case 984: return Icons.zoom_out;
        break;
        case 985: return Icons.zoom_out_map;
        break;
        default : return Icons.airplanemode_active;
      }
    }
}